### ISSUE TITLE
Add Protomux.channels map

### ISSUE THREAD

**Issue by Nuhvi** [mafintosh/protomux#2]
I found it useful to access the channels of a protomux from a Hypercore's replication stream:
```js
const channels = connection.userData._local
```
then loop through it to find the channel I want
```js
let channel;
for (const c of channels) {
    if (c.protocol === 'foo') channel = c;
}
``` 

Can I open a PR for adding a `channels` getter?
```js
get channels() {
   return Object.fromEntries(this._local.map(channel => [channel.protocol, channel]))
}
```

**Comment by mafintosh** [comment]
The instance is actually iterable, so you can just do:

```js
for (const channel of muxer) { ... }
```

Docs PR welcome

**Comment by Nuhvi** [comment]
That is cool!
